#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servoSonar,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//move forward for 1 foot, then stop
	motor[motorL]=100;
	motor[motorR]=100;
	wait1Msec(1000);

	motor[motorL]=0;
	motor[motorR]=0;

	//turn 90 degrees, and stop
	motor[motorL]=100;
	motor[motorR]=0;
	wait10Msec(150);

	motor[motorL]=0;
	motor[motorR]=0;
	wait1Msec(500);

	//Back up 2 feet, and stop
	motor[motorL]=-100;
	motor[motorR]=-100;
	wait1Msec(1000);

	motor[motorL]=0;
	motor[motorR]=0;

	//Servo move 90 degrees
	servo[servoSonar]=228;
	wait1Msec(500);

	servo[servoSonar]=110;
	wait1Msec(500);
}
