#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FrontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     BackLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    basketServo,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "joystickDriver.c"

void forward100()
{
	motor[FrontLeft]=100;
	motor[FrontRight]=100;
	motor[BackLeft]=100;
	motor[BackRight]=100;
}

void turnLeft()
{
	motor[FrontLeft]=-100;
	motor[FrontRight]=-100;
	motor[BackLeft]=100;
	motor[BackRight]=100;
	wait1Msec(1000);
}

void turnRight()
{
	motor[FrontLeft]=100;
	motor[FrontRight]=100;
	motor[BackLeft]=-100;
	motor[BackRight]=-100;
	wait1Msec(1000);
}

void park()
{
	motor[FrontLeft]=0;
	motor[FrontRight]=0;
	motor[BackLeft]=0;
	motor[BackRight]=0;
}

void jerk()
{
	forward100();
	wait1Msec(100);
	park();
}

#define bucketTime 2000
#define armTime 1600
const int basketServoDown=200;
const int basketServoUp=40;
const int armMotorUp=100;
task main()
{

	/*forward100(); //move to basket
	wait1Msec(110); //travel time //used to be 367
	// ^^^Method Deprecated!^^^
	*/
	jerk();
	servo[basketServo]=basketServoUp; //raise bucket
	wait1Msec(bucketTime); //wait for bucket to raise

	motor[armMotor]=armMotorUp; //raise arm
	wait1Msec(armTime); //wait for arm and bucket
	motor[armMotor]=0; //stop the arm

	wait1Msec(bucketTime); //wait for no momentum
	servo[basketServo]=basketServoDown; //drop bucket and cube
	wait1Msec(bucketTime); //process time //used to be 2x

	/*park(); //stop at basket //used to be before basket down
	// ^^^Deprecated!^^^ */

	servo[basketServo]=basketServoUp;
	wait1Msec(bucketTime);

	/*motor[armMotor]=-armMotorUp; //lower the arm
	wait1Msec(armTime);  //wait for the arm to lower
	motor[armMotor]=0;

	turnRight(); //turn right (because the robot is backwards)

	forward100(); //move to position for parking on the ramp
	wait1Msec(661); //


	turnRight();

	forward100();
	wait1Msec(1322);

	park();*/
}
