#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     EOPD,           sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorLB,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLF,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorRB,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorRF,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorRamp,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servoMarm,            tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servoSensor,          tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void debugmode();
void Initialize();

const int MP=50;
const int DZ=10;
const int DispenserH=2200;																//Encoder Value of the Lift when the lift reaches the height of the dispenser

task main()
{
	Initialize();
	int CurrentClaw=0;
	bool MoveUpToDis = false;																//Move Up to Dispenser height
	bool MoveDownToDis = false;															//Move Down to Dispenser Height
	int MotorRS=0;
	int MotorLS=0;
	bool ButtonHold = false;																//Is Button 5 being held Down?
	servoChangeRate[servoClaw]=2;	//added by OG
	while (true){
		getJoystickSettings(joystick);
		CurrentClaw=ServoValue[servoClaw];
//****************************
		if(joy1Btn(7)==true){
			motor[motorRamp]=50;
		}
		else if(joy1Btn(8)==true){
			motor[motorRamp]=-80;
		}
		else {
			motor[motorRamp]=0;
		}
//*****************************************
		if (joy1Btn(5) || joy1Btn(6)){												//Fast Driving mode: Hold down 5 or 6
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){					//Left motor
				MotorLS=(joystick.joy1_y1*100)/128;
				motor[motorLF]=MotorLS;
				motor[motorLB]=MotorLS;
			}
			else {
				motor[motorLF]=0;
				motor[motorLB]=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){					//Right motor
				MotorRS=(joystick.joy1_y2*100)/128;
				motor[motorRF]=MotorRS;
				motor[motorRB]=MotorRS;
			}
			else{
				motor[motorRF]=0;
				motor[motorRB]=0;
			}
		}
		else{																									//Slow Driving Mode: Normal circumstances
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){					//Left motor
				MotorLS=(joystick.joy1_y1*MP)/128;
				motor[motorLF]=MotorLS;
				motor[motorLB]=MotorLS;
			}
			else {
				motor[motorLF]=0;
				motor[motorLB]=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){					//Right motor
				MotorRS=(joystick.joy1_y2*MP)/128;
				motor[motorRF]=MotorRS;
				motor[motorRB]=MotorRS;
			}
			else{
				motor[motorRF]=0;
				motor[motorRB]=0;
			}
		}
		if (joystick.joy2_y1>DZ||joystick.joy2_y1<-DZ){				//Lift motor control
			motor[motorLift1]=(joystick.joy2_y1*50)/128;
		}
		else {
			motor[motorLift1]=0;
		}
		if (joystick.joy2_y2>50){															//Claw motor: Top position
			servo[servoClaw]=38; //changed by OG
		}
		else if (joystick.joy2_y2<-50){												//Claw motor: Bottom Position
			servo[servoClaw]=100;//changed by OG
		}
		else if (joy2Btn(7)==true){														//Claw motor: Floor Position
			servo[servoClaw]=160; // changed by OG
		}
		if ((joy1Btn(9)&joy1Btn(10))==true){									//Debug mode
			debugmode();
		}
		if ((joy2Btn(5)==true) & (ButtonHold==false)){				//Initiate & abort Finding dispenser height
			ButtonHold=true;
			if ((MoveDownToDis==false) & (MoveUpToDis==false)){			//Initiate Finding dispenser height
				if (nMotorEncoder[motorLift1]>=DispenserH){
					MoveDownToDis = true;
				}
				else {
					MoveUpToDis = true;
				}
			}
			else {																									//Abort Finding dispenser height
				MoveDownToDis=false;
				MoveUpToDis=false;
				motor[motorLift1]=0;
			}
		}
		if ((joy2Btn(5)==false) & (ButtonHold==true)){				//Reset ButtonHold
			ButtonHold=false;
		}
		if (MoveUpToDis==true){																//Move Up to Dispenser Height
			if (nMotorEncoder[motorLift1]>=DispenserH){							//Move to dispenser height
				MoveUpToDis=false;
				MoveDownToDis=false;
				motor[motorLift1]=0;
			}
			else{																										//Dispenser height achieved; abort finding dispenser height
				motor[motorLift1]=50;
			}
		}
		else if (MoveDownToDis==true){												//Move Down Dispenser height
			if (nMotorEncoder[motorLift1]<=DispenserH){
				MoveUpToDis=false;
				MoveDownToDis=false;
				motor[motorLift1]=0;
			}
			else{
				motor[motorLift1]=-50;
			}
		}
		nxtDisplayTextLine(0, "LF: %d, LB: %d", motor[motorLF], motor[motorLB]);
		nxtDisplayTextLine(1, "RF: %d, RB: %d", motor[motorRF], motor[motorRB]);
		nxtDisplayTextLine(2, "Lift: %d", motor[motorLift1]);
		wait10Msec(1);
	}
}

void debugmode(){
	wait10Msec(200);
	while ((joy1Btn(9)&joy1Btn(10))==false){
		if (joy1Btn(1)==true){
			motor[motorLF]=50;
		}
		else if (joy1Btn(2)==true){
			motor[motorLF]=-50;
		}
		else {
			motor[motorLF]=0;
		}
		if (joy1Btn(3)==true){
			motor[motorLB]=50;
		}
		else if (joy1Btn(4)==true){
			motor[motorLB]=-50;
		}
		else {
			motor[motorLB]=0;
		}
		if (joy1Btn(5)==true){
			motor[motorRF]=50;
		}
		else if (joy1Btn(6)==true){
			motor[motorRF]=-50;
		}
		else {
			motor[motorRF]=0;
		}
		if (joy1Btn(7)==true){
			motor[motorRB]=50;
		}
		else if (joy1Btn(8)==true){
			motor[motorRB]=-50;
		}
		else {
			motor[motorRB]=0;
		}
		if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
			motor[motorRamp]=(joystick.joy1_y2*25)/128;
		}
		else{
			motor[motorRamp]=0;
		}
		if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
			motor[motorLift1]=(joystick.joy1_y1*25)/128;
		}
		else{
			motor[motorLift1]=0;
		}
		wait10Msec(1);
	}
	wait10Msec(200);
}

void Initialize(){
	servo[servoClaw]=38;
	servo[servoMarm]=240;
	servo[servoSensor]=185;
	nMotorEncoder[motorLift1]=0;
}
