#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LightR,         sensorLightActive)
#pragma config(Sensor, S3,     LightL,         sensorLightActive)
#pragma config(Sensor, S4,     EOPD,           sensorI2CCustom)
#pragma config(Motor,  motorA,          motorWall,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorLF,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLB,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorRF,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorRB,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servoMarm,            tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servoSensor,          tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("joystickSimple")
#include "drivers/hitechnic-sensormux.h"
#include "JoystickDriver.c"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-eopd.h"
#include "drivers/hitechnic-colour-v2.h"
#include "drivers/lego-touch.h"

void Initialize();										//Initialize the robot

task main()
{
	Initialize();
	while (true){
		nxtDisplayTextLine(0, "LightL: %d", SensorValue[LightL]);
		nxtDisplayTextLine(1, "LightR: %d", SensorValue[LightR]);
		nxtDisplayTextLine(2, "EOPD: %d", HTEOPDreadRaw(EOPD));
		wait10Msec(1);
	}
}

void Initialize(){
	HTEOPDsetLongRange(EOPD);
	servo[servoClaw]=38;
	servo[servoMarm]=240;
	servo[servoSensor]=185;
	wait10Msec(150);
	nMotorEncoder[motorLift1]=0;
	motor[motorLift1]=50;
	while(nMotorEncoder[motorLift1]<5000){
		nxtDisplayTextLine(0, "%d", nMotorEncoder[motorLift1]);
		wait10Msec(1);
	}
	motor[motorLift1]=0;
	servo[servoSensor]=15;
}
