#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LightR,         sensorLightActive)
#pragma config(Sensor, S3,     LightL,         sensorLightActive)
#pragma config(Sensor, S4,     EOPD,           sensorI2CCustom)
#pragma config(Motor,  motorA,          motorWall,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorLF,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLB,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorRF,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorRB,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void debugmode();

const int DZ=10;

task main()
{
	int CurrentClaw=0;
	servo[servoClaw]=45;
	while (true){
		getJoystickSettings(joystick);
		CurrentClaw=ServoValue[servoClaw];
		if (joy1Btn(11) || joy1Btn(12)){
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
				motor[motorLF]=(joystick.joy1_y1*100)/128;
				motor[motorLB]=(joystick.joy1_y1*100)/128;
			}
			else {
				motor[motorLF]=0;
				motor[motorLB]=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
				motor[motorRF]=(joystick.joy1_y2*100)/128;
				motor[motorRB]=(joystick.joy1_y2*100)/128;
			}
			else{
				motor[motorRF]=0;
				motor[motorRB]=0;
			}
		}
		else{
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
				motor[motorLF]=(joystick.joy1_y1*25)/128;
				motor[motorLB]=(joystick.joy1_y1*25)/128;
			}
			else {
				motor[motorLF]=0;
				motor[motorLB]=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
				motor[motorRF]=(joystick.joy1_y2*25)/128;
				motor[motorRB]=(joystick.joy1_y2*25)/128;
			}
			else{
				motor[motorRF]=0;
				motor[motorRB]=0;
			}
		}
		if (joy1Btn(5)==true){
			motor[motorLift1]=50;
		}
		else if (joy1Btn(7)==true){
			motor[motorLift1]=-50;
		}
		else{
			motor[motorLift1]=0;
		}
		if (joy1Btn(6)){
			servo[servoClaw]=45;
		}
		else if (joy1Btn(8)){
			servo[servoClaw]=110;
		}
		if ((joy1Btn(9)&joy1Btn(10))==true){
			debugmode();
		}
		nxtDisplayTextLine(0, "LF: %d, LB: %d", motor[motorLF], motor[motorLB]);
		nxtDisplayTextLine(1, "RF: %d, RB: %d", motor[motorRF], motor[motorRB]);
		wait10Msec(1);
	}
}

void debugmode(){
	wait10Msec(200);
	while ((joy1Btn(9)&joy1Btn(10))==false){
		if (joy1Btn(1)==true){
			motor[motorLF]=50;
		}
		else if (joy1Btn(2)==true){
			motor[motorLF]=-50;
		}
		else {
			motor[motorLF]=0;
		}
		if (joy1Btn(3)==true){
			motor[motorLB]=50;
		}
		else if (joy1Btn(4)==true){
			motor[motorLB]=-50;
		}
		else {
			motor[motorLB]=0;
		}
		if (joy1Btn(5)==true){
			motor[motorRF]=50;
		}
		else if (joy1Btn(6)==true){
			motor[motorRF]=-50;
		}
		else {
			motor[motorRF]=0;
		}
		if (joy1Btn(7)==true){
			motor[motorRB]=50;
		}
		else if (joy1Btn(8)==true){
			motor[motorRB]=-50;
		}
		else {
			motor[motorRB]=0;
		}
		if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
			motor[motorLift2]=(joystick.joy1_y2*25)/128;
		}
		else{
			motor[motorLift2]=0;
		}
		if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
			motor[motorLift1]=(joystick.joy1_y1*25)/128;
		}
		else{
			motor[motorLift1]=0;
		}
		wait10Msec(1);
	}
	wait10Msec(200);
}
