#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LightR,         sensorLightActive)
#pragma config(Sensor, S3,     LightL,         sensorLightActive)
#pragma config(Sensor, S4,     EOPD,           sensorI2CCustom)
#pragma config(Motor,  motorA,          motorWall,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servoClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoAuto,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

const int DZ=10;

task main()
{
	servoChangeRate[servoClaw]=2;
	servoChangeRate[servoAuto]=2;
	servo[servoAuto]=255;
	servo[servoClaw]=0;
	wait1Msec(2000);

	int CurrentClaw=0;
	while (true){
		getJoystickSettings(joystick);
		CurrentClaw=ServoValue[servoClaw];
		if (joy1Btn(11) || joy1Btn(12)){
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
				motor[motorL]=(joystick.joy1_y1*100)/128;
			}
			else {
				motor[motorL]=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
				motor[motorR]=(joystick.joy1_y2*100)/128;
			}
			else{
				motor[motorR]=0;
			}
		}
		else{
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
				motor[motorL]=(joystick.joy1_y1*50)/128;
			}
			else {
				motor[motorL]=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
				motor[motorR]=(joystick.joy1_y2*50)/128;
			}
			else{
				motor[motorR]=0;
			}
		}
		if (joy1Btn(5)==true){
			motor[motorLift1]=50;
		}
		else if (joy1Btn(7)==true){
			motor[motorLift1]=-50;
		}
		else{
			motor[motorLift1]=0;
		}
		if (joy1Btn(6)){
			servo[servoClaw]=45;
		}
		else if (joy1Btn(8)){
			servo[servoClaw]=110;
		}
		nxtDisplayTextLine(0, "L: %d , R: %d", motor[motorL], motor[motorR]);
		wait10Msec(1);
	}
}
