#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     LightR,         sensorLightActive)
#pragma config(Sensor, S3,     LightL,         sensorLightActive)
#pragma config(Sensor, S4,     EOPD,           sensorI2CCustom)
#pragma config(Motor,  motorA,          motorWall,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorLF,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLB,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorRF,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorRB,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servoMarm,            tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servoSensor,          tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void debugmode();
void Initialize();

const int DZ=10;
const int DispenserH=2800;																//Encoder Value of the Lift when the lift reaches the height of the dispenser

task main()
{
//	Initialize();
	int CurrentClaw=0;
	bool MoveUpToDis = false;																//Move Up to Dispenser height
	bool MoveDownToDis = false;															//Move Down to Dispenser Height
	bool MoveUpALittle = false;															//Move up a small amount to pick up ring
	while (true){
		getJoystickSettings(joystick);
		CurrentClaw=ServoValue[servoClaw];
		if (joy1Btn(11) || joy1Btn(12)){
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
				motor[motorLF]=(joystick.joy1_y1*100)/128;
				motor[motorLB]=(joystick.joy1_y1*100)/128;
			}
			else {
				motor[motorLF]=0;
				motor[motorLB]=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
				motor[motorRF]=(joystick.joy1_y2*100)/128;
				motor[motorRB]=(joystick.joy1_y2*100)/128;
			}
			else{
				motor[motorRF]=0;
				motor[motorRB]=0;
			}
		}
		else{
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
				motor[motorLF]=(joystick.joy1_y1*30)/128;
				motor[motorLB]=(joystick.joy1_y1*30)/128;
			}
			else {
				motor[motorLF]=0;
				motor[motorLB]=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
				motor[motorRF]=(joystick.joy1_y2*30)/128;
				motor[motorRB]=(joystick.joy1_y2*30)/128;
			}
			else{
				motor[motorRF]=0;
				motor[motorRB]=0;
			}
		}
		if (joystick.joy2_y1>DZ||joystick.joy2_y1<-DZ){
			motor[motorLift1]=(joystick.joy2_y1*50)/128;
		}
		else {
			motor[motorLift1]=0;
		}
		if (joystick.joy2_y2>50){
			servo[servoClaw]=45;
		}
		else if (joystick.joy2_y2<-50){
			servo[servoClaw]=110;
		}
		if ((joy1Btn(9)&joy1Btn(10))==true){
			debugmode();
		}
		if (joy2Btn(5)==true){
			if (nMotorEncoder[motorLift1]>=DispenserH){
				MoveDownToDis = true;
			}
			else {
				MoveUpToDis = true;
			}
		}
		if (MoveUpToDis==true){
			if (nMotorEncoder[motorLift1]>=DispenserH){
				MoveUpToDis=false;
				MoveDownToDis=false;
				motor[motorLift1]=0;
			}
			else{
				motor[motorLift1]=50;
			}
		}
		else if (MoveDownToDis==true){
			if (nMotorEncoder[motorLift1]<=DispenserH){
				MoveUpToDis=false;
				MoveDownToDis=false;
				motor[motorLift1]=0;
			}
			else{
				motor[motorLift1]=-50;
			}
		}
		nxtDisplayTextLine(0, "LF: %d, LB: %d", motor[motorLF], motor[motorLB]);
		nxtDisplayTextLine(1, "RF: %d, RB: %d", motor[motorRF], motor[motorRB]);
		nxtDisplayTextLine(2, "Lift: %d", motor[motorLift1]);
		wait10Msec(1);
	}
}

void debugmode(){
	wait10Msec(200);
	while ((joy1Btn(9)&joy1Btn(10))==false){
		if (joy1Btn(1)==true){
			motor[motorLF]=50;
		}
		else if (joy1Btn(2)==true){
			motor[motorLF]=-50;
		}
		else {
			motor[motorLF]=0;
		}
		if (joy1Btn(3)==true){
			motor[motorLB]=50;
		}
		else if (joy1Btn(4)==true){
			motor[motorLB]=-50;
		}
		else {
			motor[motorLB]=0;
		}
		if (joy1Btn(5)==true){
			motor[motorRF]=50;
		}
		else if (joy1Btn(6)==true){
			motor[motorRF]=-50;
		}
		else {
			motor[motorRF]=0;
		}
		if (joy1Btn(7)==true){
			motor[motorRB]=50;
		}
		else if (joy1Btn(8)==true){
			motor[motorRB]=-50;
		}
		else {
			motor[motorRB]=0;
		}
		if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
			motor[motorLift2]=(joystick.joy1_y2*25)/128;
		}
		else{
			motor[motorLift2]=0;
		}
		if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
			motor[motorLift1]=(joystick.joy1_y1*25)/128;
		}
		else{
			motor[motorLift1]=0;
		}
		wait10Msec(1);
	}
	wait10Msec(200);
}

void Initialize(){
	servo[servoClaw]=45;
	servo[servoMarm]=15;
	servo[servoSensor]=200;
	wait10Msec(150);
	nMotorEncoder[motorLift1]=0;
	motor[motorLift1]=50;
	while(nMotorEncoder[motorLift1]<5000){
		nxtDisplayTextLine(0, "%d", nMotorEncoder[motorLift1]);
		wait10Msec(1);
	}
	motor[motorLift1]=0;
}
