#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     touchSensor,    sensorNone)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FrontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BackLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FrontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    basketServo,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"

//Defines button values to substitute for names
#define SWEEPERBUTTON 5
#define ARMJOYSTICK joystick.joy2_y1
#define BASKETUPBUTTON 6

#define BASKETDOWNBUTTON 7
#define FLAGBUTTON 8

//This section defines the constaints used throughout the code
const int sweeperOn=-100;
const int sweeperOff=0;

const int deadZone=5;
const int armMotorUp=100;

const int basketServoStart=200;
const int basketServoUp=40;

const int flagMotorOn=100;

int scaleMotor(int joyValue);

task main()
{
	//false=off/start position/etc.
	bool sweeperState=false;
	bool flagState=false;
	servo[basketServo]=basketServoUp;

	while(true)
	{
		//Riley's code
		if(abs(joystick.joy1_y1)>deadZone)
		{
			motor[FrontLeft]=scaleMotor(joystick.joy1_y1);
			motor[BackLeft]=scaleMotor(joystick.joy1_y1);
			//debug code
			/*
			nxtDisplayTextLine(1, "%d",scaleMotor(joystick.joy1_y1) );
			wait1Msec(5000);
			*/
		}
		else
		{
			motor[FrontLeft]=0;
			motor[BackLeft]=0;
		}
		if(abs(joystick.joy1_y2)>deadZone)
		{
			motor[FrontRight]=scaleMotor(joystick.joy1_y2);
			motor[BackRight]=scaleMotor(joystick.joy1_y2);
		}
		else
		{
			motor[FrontRight]=0;
			motor[BackRight]=0;
		}
		//End of Riley's code

		//Toggling the sweeper
		if(joy2Btn(SWEEPERBUTTON)==true && sweeperState==false)
		{
			motor[sweeper]=sweeperOn;
			sweeperState=true;
		}
		else if(joy2Btn(SWEEPERBUTTON)==true && sweeperState==true)
		{
			motor[sweeper]=sweeperOff;
			sweeperState=false;
		}

		//Moving the arm up or down
		if((abs(ARMJOYSTICK))>deadZone && ARMJOYSTICK>0)
		{
			motor[armMotor]=armMotorUp;
		}
		else if((abs(ARMJOYSTICK))>deadZone && ARMJOYSTICK<0)
		{
			while(SensorValue[touchSensor]==0)
			{
				motor[armMotor]=-armMotorUp;
			}
			motor[armMotor]=armMotorUp;
			wait1Msec(50);
			motor[armMotor]=0;
		}
		else
		{
			motor[armMotor]=0;
		}

		//Change the basket servo position
		if(joy2Btn(BASKETUPBUTTON)==true)
		{
			servo[basketServo]=basketServoUp;
		}
		else if(joy2Btn(BASKETDOWNBUTTON)==true)
		{
			servo[basketServo]=basketServoStart;
		}

		//Turns the flag motor on/off
		if(joy2Btn(FLAGBUTTON)==true && flagState==false)
		{
			motor[flagMotor]=flagMotorOn;
			flagState=true;
		}
		else if(joy2Btn(FLAGBUTTON)==true && flagState==true)
		{
			motor[flagMotor]=0;
			flagState=false;
		}
		wait1Msec(1);
	}
}
//logarithmic scale for motors
int scaleMotor(int joyValue)
{
	int direction=joyValue/abs(joyValue);
	float ratio=(joyValue*joyValue)/(128.0*128.0);
	int scaleMotor=(ratio*100)*direction;
	//debug code
	/*
	nxtDisplayTextLine(1, "%d", scaleMotor);
	wait1Msec(5000);
	return scaleMotor;
	*/
}
