#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     EOPD,           sensorI2CCustom)
#pragma config(Motor,  motorA,          motorWall,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorLB,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLF,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorRB,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorRF,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servoMarm,            tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servoSensor,          tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-eopd.h"
#include "drivers/hitechnic-colour-v2.h"
#include "drivers/lego-touch.h"
#include "moveAndTurnRobotIndefiniteDistance.c"
#include "moveTurnRobotWithDefinedDistanceAndTurnAngles.c"
#include "preLineFollowOption1.c"
#include "lineFollowingDvr.c"
#include "whichColumnIsBeaconOn.c"
#include "commonFunctions.c"


/** ***************************************************************************
* Light sensors on Mux port 3 and 4
*/

/*
const tMUXSensor LightR = msensor_S2_3;
const tMUXSensor LightL = msensor_S2_4;
*/

const int motorPowerLineFollow=15; //motorPower for line follower driver
const int motorPowerGeneral=25;
//const int EWT=20;				//Wobble Timer. Time given for the Elevator motors to stop wobbling
const int WWT=20;				//Wobble Timer. Time given for the drive motors to stop wobbling


void Initialize(){
	HTEOPDsetLongRange(EOPD);
	servo[servoClaw]=58;
	servo[servoMarm]=240;
	servo[servoSensor]=185;
	wait10Msec(150);
	nMotorEncoder[motorLift1]=0;
	nMotorEncoder[motorLB]=0;
	nMotorEncoder[motorRB]=0;
	motor[motorLift1]=50;
	while(nMotorEncoder[motorLift1]<6200){
		nxtDisplayTextLine(0, "%d", nMotorEncoder[motorLift1]);
		wait10Msec(1);
	}
	motor[motorLift1]=0;
	servo[servoSensor]=17;
}

task main(){
	Initialize();																										//Initialize
	wait10Msec(200);
/** ***************************************
* move forward to close to the middle white line
*/

	Forward(80,40); //move forward 48 inches
	Stopbot();
	wait1Msec(20);
	wait10Msec(100000);

	preLineFollowTweak();

	LineFollow(motorPowerLineFollow);																								//line follow
	Stopbot();
	wait10Msec(WWT);

	servo[servoMarm]=20;																						//Place ring
	servo[servoClaw]=100;
	wait10Msec(200);
	motor[motorLift1]=-50;
	while(nMotorEncoder[motorLift1]>5000){
		nxtDisplayTextLine(0, "%d", nMotorEncoder[motorLift1]);
		wait10Msec(1);
	}
	motor[motorLift1]=0;
	wait10Msec(50);
	/*
	Right();
	wait10Msec(50);
	*/
	Backward(motorPowerGeneral,10);
	wait10Msec(100);
	Stopbot();
	wait10Msec(WWT);
}
