#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     Motor,          sensorI2CMuxController)
#pragma config(Sensor, S2,     Touch,          sensorTouch)
#pragma config(Sensor, S3,     Color,          sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BackLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FrontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     ZiptieAxel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     FlagMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    CubeFlipper,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-op sample code - Oliver Ge
//
// This sample program is your starting point for 4324 Tele-op tank drive.
// 1) Add a lot of comments and spacing to your program!
// 2) Constant definition - remember why we need constant?
// 3) Talk to hardware team, draw a wiring diagram of the robot. Be very clear which motor goes which controller
// 4) Keep in mind wiring changes from time, think about how to make your program adapatable
// 5) If you find you are typing a certain codes over and over, try to use a function
// 6) For now, I want to you to declare functions first and place the functions below task main.
// 7) Always remember to stop motor movements after moving
//
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "joystickDriver.c"

/*
This secction defines the constants you are going to
use in the program
*/

const int deadZone=5; // define deadzone
const int servoStart=0;
const int servoStop=100;


task main()
{
	//servo and motor initialization code here
	servo[CubeFlipper]=255;
	motor[FlagMotor]=0;

	//main program loop defined in this section
	while(true)
	{
		getJoystickSettings(joystick);

		// flag motor control code
		if (joystick.joy1_Buttons & 1)
		{
			motor[FlagMotor]=100;
		}

		/* *** arm motor control code here, remember, you need to ****************/
		//**** set the basket servo when moving the arm **************************/
		if (joystick.joy1_Buttons & 2)
		{
			//servo movement, hardware team may want this to be automatic
			// always discuss with the team
			//arm control code

		}
		else if (joystick.joy1_Buttons &3)
		{
			//arm move the other direction
		}
		else
		{
			//stop motors
		}


		/* **** Drive motor contorl, think about how to use logarithmic power control ********
		// **** and how to add a button to cut the motor to half *****************************/
		if (joystick.joy1_y1>deadZone && joystick.joy1_y2>deadZone)
		{
			motor[FrontLeft]=joystick.joy1_y1;
			motor[BackLeft]=joystick.joy1_y1;
			motor[FrontRight]=joystick.joy1_y2;
			motor[BackRight]=joystick.joy1_y2;
		}
		else
		{
			motor[FrontLeft]=0;
			motor[BackLeft]=0;
			motor[FrontRight]=0;
			motor[BackRight]=0;
		}

		//Scoop Controls
		motor[ZiptieAxel]=100;
		wait1Msec(1);

	}
}
