#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S3,     LightSensor,    sensorLightInactive)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servoSonar,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait10Msec(1);
	nxtDisplayCenteredTextLine(1, "%d", SensorValue[LightSensor]);
	wait10Msec(100);

	while(true)
	{
		if (SensorValue[LightSensor]<32)
		{
	//		nxtDisplayCenteredTextLine(1, "%d", SensorValue[LightSensor]);
	//		wait10Msec(100);
			motor[motorL]=35;
			motor[motorR]=5;
			wait1Msec(1);
		}
		else
		{
			motor[motorL]=5;
			motor[motorR]=35;
			wait1Msec(1);
		}
	}
}
