#pragma config(Motor,  motorA,          lm,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rm,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          nm,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(Tetrix)
#include "MotorControlDriver.c"

task main()
{

  eraseDisplay();
  //nMotorPIDSpeedCtrl[rm] = mtrSpeedReg;
  //nMotorPIDSpeedCtrl[lm] = mtrSpeedReg;
  initializeIndividualMotor(rm, 1);
  initializeIndividualMotor(lm, 1);
  initialializeMotorControl(200);
  setMotorPower(lm,  100 );
  //setMotorPower(nm,  100 );
  setMotorPower(rm,  100 );

  //for(int i=0; i<=200; i++)
  //{
  //	if(i<100)
  //	{
	 //   motor[lm] = i;
	 //   motor[rm] = i;
	 // }
	 // else
  //	{
	 //   motor[lm] = 100;
	 //   motor[rm] = 100;
	 // }
	 // nxtDisplayCenteredTextLine(3, "right  %d", i );
	 // nxtDisplayCenteredTextLine(4, " left  %d", i );
	 // wait1Msec(200);
  //}

  wait1Msec(22000);

  //setMotorPower(lm,  0 );
  //setMotorPower(rm,  0 );

  //wait1Msec(22000);

  motorChangeTimeInterval = 10;
  stopMotorControl();

} // task main
