#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     TouchSensor,    sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     FrontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BackLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FrontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     BackRight,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     CubeSpinner,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     FlagRaiser,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    CubeBox,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "joystickDriver.c"

const int deadZone=5;

int powerConversion(int joyValue);


task main()
{
	while(true)
	{
		if(joystick.joy1_y1>deadZone && joystick.joy1_y2>deadZone)
		{
			motor(FrontLeft) = (joystick.joy1_y1*100)/128;
			motor(BackLeft) = (joystick.joy1_y1*100)/128;
			motor(FrontRight) = (joystick.joy1_y2*100)/128;
			motor(BackRight) = (joystick.joy1_y2*100)/128;
		}
		else
		{
			motor(FrontLeft)=0;
			motor(BackLeft)=0;
			motor(FrontRight)=0;
			motor(BackRight)=0;
		}
	}
}
