#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     Touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    ServoSensor,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int servoStart=118;
const int servoStop=0;

task main()
{
	//initialize sensor posistion
	servo[ServoSensor]=servoStart;

	//Move forward until sensor touches something and stop
	while(SensorValue[Touch]==0)
	{
		motor[motorL]=30;
		motor[motorR]=30;
	}
	motor[motorL]=0;
	motor[motorR]=0;
	wait10Msec(1);

	//Back up 1 inch and stop
	motor[motorL]=-100;
	motor[motorR]=-100;
	wait10Msec(100);

	motor[motorL]=0;
	motor[motorR]=0;

	//Turn sensor to the left
	servo[ServoSensor]=servoStop;
	wait10Msec(1);
	}
