#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LightR,         sensorLightActive)
#pragma config(Sensor, S3,     LightL,         sensorLightActive)
#pragma config(Sensor, S4,     EOPD,           sensorI2CCustom)
#pragma config(Motor,  motorA,          motorWall,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorLF,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLB,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorRF,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorRB,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servoClaw,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servoMarm,            tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servoSensor,          tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "MotorControlDriver.c"

void debugmode();
void Initialize();

const int DZ=10;
const int DispenserH=2800;																//Encoder Value of the Lift when the lift reaches the height of the dispenser

task main()
{
	Initialize();
	int CurrentClaw=0;
	bool MoveUpToDis = false;																//Move Up to Dispenser height
	bool MoveDownToDis = false;															//Move Down to Dispenser Height
	servoChangeRate[servoClaw]=2;	//added by OG
	int leftPower=0;
	int rightPower=0;
	int armPower=0;
	
	// disable joystick diagnostic
  initializeIndividualMotor(motorLF, 2);
  initializeIndividualMotor(motorLB, 2);
  initializeIndividualMotor(motorRF, 2);
  initializeIndividualMotor(motorRB, 2);
  initializeIndividualMotor(motorLift1, 2);
  initialializeMotorControl(2);
  
	while (true){
		getJoystickSettings(joystick);
		CurrentClaw=ServoValue[servoClaw];
		if (joy1Btn(11) || joy1Btn(12)){
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
				leftPower=(joystick.joy1_y1*100)/128;
			}
			else {
				leftPower=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
				rightPower=(joystick.joy1_y2*100)/128;
			}
			else{
				rightPower=0;
			}
		}
		else{
			if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
				leftPower=(joystick.joy1_y1*60)/128;
			}
			else {
				leftPower=0;
			}
			if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
				rightPower=(joystick.joy1_y2*60)/128;
			}
			else{
				rightPower=0;
			}
		}
		if (joystick.joy2_y1>DZ||joystick.joy2_y1<-DZ){
				armPower=(joystick.joy2_y1*50)/128;
		}
		else {
				armPower=0;
		}
		if (joystick.joy2_y2>50){
			servo[servoClaw]=38; //changed by OG
		}
		else if (joystick.joy2_y2<-50){
			servo[servoClaw]=100;//changed by OG
		}
		else if (joy2Btn(7)==true){
			servo[servoClaw]=160; // changed by OG
		}
		if ((joy1Btn(9)&joy1Btn(10))==true){
			debugmode();
		}
		if (joy2Btn(5)==true){
			if (nMotorEncoder[motorLift1]>=DispenserH){
				MoveDownToDis = true;
			}
			else {
				MoveUpToDis = true;
			}
		}
		if (MoveUpToDis==true){
			if (nMotorEncoder[motorLift1]>=DispenserH){
				MoveUpToDis=false;
				MoveDownToDis=false;
				armPower=0;
			}
			else{
				armPower=50;
			}
		}
		else if (MoveDownToDis==true){
			if (nMotorEncoder[motorLift1]<=DispenserH){
				MoveUpToDis=false;
				MoveDownToDis=false;
				armPower=0;
			}
			else{
				armPower=-50;
			}
		}
/*	
	nxtDisplayTextLine(0, "LF: %d, LB: %d", motor[motorLF], motor[motorLB]);
		nxtDisplayTextLine(1, "RF: %d, RB: %d", motor[motorRF], motor[motorRB]);
		nxtDisplayTextLine(2, "Lift: %d", motor[motorLift1]);
		wait10Msec(1);
*/	
	setMotorPower(motorLF,  leftPower);
	setMotorPower(motorLB,  leftPower);
	setMotorPower(motorRF, rightPower);
	setMotorPower(motorRB, rightPower);
	setMotorPower(motorLift1, armPower);
	}
}

void debugmode(){
	wait10Msec(200);
	while ((joy1Btn(9)&joy1Btn(10))==false){
		if (joy1Btn(1)==true){
			motor[motorLF]=50;
		}
		else if (joy1Btn(2)==true){
			motor[motorLF]=-50;
		}
		else {
			motor[motorLF]=0;
		}
		if (joy1Btn(3)==true){
			motor[motorLB]=50;
		}
		else if (joy1Btn(4)==true){
			motor[motorLB]=-50;
		}
		else {
			motor[motorLB]=0;
		}
		if (joy1Btn(5)==true){
			motor[motorRF]=50;
		}
		else if (joy1Btn(6)==true){
			motor[motorRF]=-50;
		}
		else {
			motor[motorRF]=0;
		}
		if (joy1Btn(7)==true){
			motor[motorRB]=50;
		}
		else if (joy1Btn(8)==true){
			motor[motorRB]=-50;
		}
		else {
			motor[motorRB]=0;
		}
		if (joystick.joy1_y2>DZ||joystick.joy1_y2<-DZ){
			motor[motorLift2]=(joystick.joy1_y2*25)/128;
		}
		else{
			motor[motorLift2]=0;
		}
		if (joystick.joy1_y1>DZ||joystick.joy1_y1<-DZ){
			motor[motorLift1]=(joystick.joy1_y1*25)/128;
		}
		else{
			motor[motorLift1]=0;
		}
		wait10Msec(1);
	}
	wait10Msec(200);
}

void Initialize(){
	servo[servoClaw]=38;
	servo[servoMarm]=240;
	servo[servoSensor]=185;
	nMotorEncoder[motorLift1]=0;
}
