#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    basketServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"

//Defines button values to substitute for names
#define SWEEPERBUTTON 5
#define ARMJOYSTICK joystick.joy2_y1
#define BASKETUPBUTTON 6

#define BASKETDOWNBUTTON 7
#define FLAGBUTTON 8

//This section defines the constaints used throughout the code
const int sweeperOn=100;
const int sweeperOff=0;

const int deadZone=5;
const int armMotorUp=100;

const int basketServoStart=0;
const int basketServoUp=250;

const int flagMotorOn=100;


//*TODO* Add code to initialize servos and motors

task main()
{
	//false=off/start position/etc.
	bool sweeperState=false;
	bool flagState=false;

	while(true)
	{
		getJoystickSettings(joystick);

		//Toggling the sweeper
		if(joy2Btn(SWEEPERBUTTON)==true && sweeperState==false)
		{
			motor[sweeper]=sweeperOn;
			sweeperState=true;
		}
		else if(joy2Btn(SWEEPERBUTTON)==true && sweeperState==true)
		{
			motor[sweeper]=sweeperOff;
			sweeperState=false;
		}

		//Moving the arm up or down
		if((abs(ARMJOYSTICK))>deadZone && ARMJOYSTICK>0)
		{
			motor[armMotor]=armMotorUp;
		}
		else if((abs(ARMJOYSTICK))>deadZone && ARMJOYSTICK<0)
		{
			while(SensorValue[touchSensor]==0)
			{
				motor[armMotor]=-armMotorUp;
			}
			motor[armMotor]=armMotorUp;
			wait1Msec(50);
			motor[armMotor]=0;
		}
		else
		{
			motor[armMotor]=0;
		}

		//Change the basket servo position
		if(joy2Btn(BASKETUPBUTTON)==true)
		{
			servo[basketServo]=basketServoUp;
		}
		else if(joy2Btn(BASKETDOWNBUTTON)==true)
		{
			servo[basketServo]=basketServoStart;
		}

		//Turns the flag motor on/off
		if(joy2Btn(FLAGBUTTON)==true && flagState==false)
		{
			motor[flagMotor]=flagMotorOn;
			flagState=true;
		}
		else if(joy2Btn(FLAGBUTTON)==true && flagState==true)
		{
			motor[flagMotor]=0;
			flagState=false;
		}
	}
}
