#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    ServoSonar,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int servoStart=118;
const int servoStop=0;

task main()
{
	//Sets touchSensor servo to initial position
	servo[ServoSonar]=servoStart;
	while(SensorValue[touch]==0)
	{
		motor[motorL]=20;
		motor[motorR]=20;
	}
	motor[motorL]=0;
	motor[motorR]=0;
	wait1Msec(100);

	motor[motorL]=-100;
	motor[motorR]=-100;
	wait10Msec(50);

	motor[motorL]=0;
	motor[motorR]=0;

	//Turns touchSensor servo to the left
	servo[ServoSonar]=servoStop;
	wait10Msec(100);
}
