#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FrontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     BackLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    basketServo,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"
//def forward=100, 100
//def turnLeft=-100, 100
//def turnRight=100, -100
void scaleMove(int leftPower, int rightPower, int driveTime)
{
	setLeft(25);
	setRight(25);
	int stepSize=3 //step size of 3 per 1Msec;
	while(motor[FrontLeft]!=leftPower && motor[FrontRight]!=rightPower && motor[BackLeft]!=leftPower && motor[BackRight]!=rightPower)
	{
		
		if(motor[FrontLeft]!=leftPower)
		{
			if(leftPower-motor[FrontLeft]<3)
			{
				stepSize=leftPower-motor[FrontLeft]
			}
			motor[FrontLeft]=motor[FrontLeft]+stepSize;
			motor[BackLeft]=motor[BackLeft]+stepSize;
		}
		if(motor[FrontRight]!=rightPower)
		{
			if(rightPower-motor[FrontRight]<3)
			{
				stepSize=rightPower-motor[FrontRight]
			}
			motor[FrontRight]=motor[FrontLeft]+3;
			motor[BackRight]=motor[BackRight]+3;
		}
		wait1Msec(1);
	}
	wait1Msec(driveTime-125);
	while(motor[FrontLeft]!=0 && motor[FrontRight]!=0 && motor[BackLeft]!=0 && motor[BackRight]!=0)
	{
		if(motor[FrontLeft]!=0)
		{
			if(motor[FrontLeft]<3)
			{
				stepSize=motor[FrontLeft]
			}
			motor[FrontLeft]=motor[FrontLeft]-stepSize;
			motor[BackLeft]=motor[BackLeft]-stepSize;
		}
		if(motor[FrontRight]!=0)
		{
			if(motor[FrontRight]<3)
			{
				stepSize=motor[FrontRight]
			}
			motor[FrontRight]=motor[FrontLeft]-stepSize;
			motor[BackRight]=motor[BackRight]-stepSize;
		}
		wait1Msec(1);
	}
}

void setMotors(int motorPower)
{
	motor[FrontLeft]=motorPower
	motor[FrontRight]=motorPower
	motor[BackLeft]=motorPower
	motor[BackRight]=motorPower
}

void setLeft(int motorPower)
{
	motor[FrontLeft]=motorPower
	motor[BackLeft]=motorPower
}

void setRight(int motorPower)
{
	motor[FrontRight]=motorPower
	motor[BackRight]=motorPower
}

/*void forward100(int driveTime)
{
	motor[FrontLeft]=100
	motor[FrontRight]=100
	motor[BackLeft]=100
	motor[BackRight]=100
	wait1Msec(driveTime)
}*/

void turnRight(int turnTime)
{
	motor[FrontLeft]=100;
	motor[FrontRight]=-100;
	motor[BackLeft]=100;
	motor[BackRight]=-100;
	wait1Msec(turnTime);
}

void turnLeft(int turnTime)
{
	motor[FrontLeft]=-100;
	motor[FrontRight]=100;
	motor[BackLeft]=-100;
	motor[BackRight]=100;
	wait1Msec(turnTime);
}

void park()
{
	motor[FrontLeft]=0;
	motor[FrontRight]=0;
	motor[BackLeft]=0;
	motor[BackRight]=0;
}

void toBasket()
{
	scaleMove(100, 100, 400) //full power forward for 400ms
	fullStop();
}

void fullStop()
{
	park();
	wait1Msec(250);
}

void reverse100()
{
	motor[FrontLeft]=-100;
	motor[FrontRight]=-100;
	motor[BackLeft]=-100;
	motor[BackRight]=-100;
}

void SetupRamp()
{
	motor[FrontLeft]=100;
	motor[FrontRight]=100;
	motor[BackLeft]=100;
	motor[BackRight]=100;
	wait1Msec(875);
}
#define bucketTime 1250
#define armTime 1850
const int basketServoDown=200;
const int basketServoUp=40;
const int armMotorUp=100;
task main()
{
	waitForStart();
	toBasket(); //move to basket
	//servo[basketServo]=basketServoUp; //raise bucket
	//wait1Msec(bucketTime); //wait for bucket to raise

	//motor[armMotor]=armMotorUp; //raise arm
	//wait1Msec(armTime); //wait for arm and bucket
	//motor[armMotor]=0; //stop the arm

	//fullStop(); //wait for no momentum
	//servo[basketServo]=basketServoDown; //drop bucket and cube
	//wait1Msec(bucketTime); //process time

	//servo[basketServo]=basketServoUp;
	//wait1Msec(bucketTime);

	//motor[armMotor]=-armMotorUp; //lower the arm
	//while(SensorValue[touchSensor]!=1) //wait for the arm to lower
	{

	}
	//motor[armMotor]=0; //stop arm at bottom
	//turnRight(500); //turn towards ramp
	//fullStop();
	//forward100(950); //move onto ramp
	//fullStop();
	//turnLeft(500);
	//fullStop();
	//forward100(2000);
	//fullStop();
}
