#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FrontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     BackLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     FrontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    basketServo,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"
//def forward=100, 100
//def turnLeft=-100, 100
//def turnRight=100, -100
void setLeft(int motorPower)
{
	motor[FrontLeft]=motorPower;
	motor[BackLeft]=motorPower;
}

void setRight(int motorPower)
{
	motor[FrontRight]=motorPower;
	motor[BackRight]=motorPower;
}

int getLeft()
{
	return motor[FrontLeft];
}

int getRight()
{
	return motor[FrontRight];
}

void scaleMove(int leftPower, int rightPower, int driveTime)
{
	int frequency=440;
	int counter=0; //cycle counter
	int numSteps=50; //number of steps to use
	int leftStep=leftPower/numSteps; //the step size of the left motors (independant of the right motors) vvv
	int rightStep=rightPower/numSteps; // is determined by the desired power divided by the number of steps
	while(motor[FrontLeft]!=leftPower || motor[FrontRight]!=rightPower) //while either the front left or right motors are not yet at the desired
	{
		if (motor[FrontLeft]!=leftPower) //if the left motors are off,
		{
			setLeft(motor[FrontLeft]+leftStep); //add the step size, note that it can be negative for reverse.
		}
		if (motor[FrontRight]!=rightPower)
		{
			setRight(motor[FrontRight]+rightStep);
		}
		wait1Msec(1);
		counter++; //bump the counter up one,
	}

	if(counter>numSteps)
	{
		motor[FrontLeft]=0;
		motor[FrontRight]=0;
		motor[BackLeft]=0;
		motor[BackRight]=0;
		string errcode="err in uploop";
		nxtDisplayString(1,"%s",errcode);
		PlayImmediateTone(frequency,10);
		StopAllTasks();
	}
		if (counter*2>driveTime||counter>=driveTime)
	{
		motor[FrontLeft]=0;
		motor[FrontRight]=0;
		motor[BackLeft]=0;
		motor[BackRight]=0;
		string errcode="err2 waitloop";
		nxtDisplayString(1, "%s", errcode);
		PlayImmediateTone(frequency,10);
		PlayImmediateTone(frequency,10);
		StopAllTasks();
	}
	//
	wait1Msec(driveTime-(numSteps*2)); //subtract the number of ms spent during stepping up, times two for same amount of time stepping down
	while(motor[FrontLeft]!=0 || motor[FrontRight]!=0) //while either front left or right motors are still running
	{
		if (motor[FrontLeft]!=0) //if the left motors are still running,
		{
			setLeft(motor[FrontLeft]-leftStep); //subtract the step size, note that it can be negative for reverse.
		}
		if (motor[FrontRight]!=0)
		{
			setRight(motor[FrontRight]-rightStep);
		}
		wait1Msec(1); //wait, and repeat until all motors are stopped
	}
}

/*void forward100(int driveTime)
{
	motor[FrontLeft]=100
	motor[FrontRight]=100
	motor[BackLeft]=100
	motor[BackRight]=100
	wait1Msec(driveTime)
}*/

void turnRight(int turnTime)
{
	motor[FrontLeft]=100;
	motor[FrontRight]=-100;
	motor[BackLeft]=100;
	motor[BackRight]=-100;
	wait1Msec(turnTime);
}

void turnLeft(int turnTime)
{
	motor[FrontLeft]=-100;
	motor[FrontRight]=100;
	motor[BackLeft]=-100;
	motor[BackRight]=100;
	wait1Msec(turnTime);
}

void park()
{
	motor[FrontLeft]=0;
	motor[FrontRight]=0;
	motor[BackLeft]=0;
	motor[BackRight]=0;
}

void fullStop()
{
	park();
	wait1Msec(200); //150
}

void toBasket()
{
	scaleMove(100, 100, 600); //full power forward for 600ms
	fullStop();
}

void reverse100()
{
	motor[FrontLeft]=-100;
	motor[FrontRight]=-100;
	motor[BackLeft]=-100;
	motor[BackRight]=-100;
}

void SetupRamp()
{
	motor[FrontLeft]=100;
	motor[FrontRight]=100;
	motor[BackLeft]=100;
	motor[BackRight]=100;
	wait1Msec(875);
}
const int touchUnpressed=0;
const int basketServoDown=180;
const int basketServoUp=15;
const int armMotorUp=100;
#define bucketTime 1000
#define armTime 1600 //1600
void cycleArm()
{
	servo[basketServo]=basketServoUp; //raise bucket
	wait1Msec(bucketTime); //wait for bucket to raise
	motor[armMotor]=armMotorUp; //raise arm
	wait1Msec(armTime); //wait for arm and bucket
	motor[armMotor]=0; //stop the arm
	fullStop(); //wait for no momentum
	servo[basketServo]=basketServoDown; //drop bucket and cube
	wait1Msec(bucketTime); //process time

	servo[basketServo]=basketServoUp;
	wait1Msec(bucketTime);

	motor[armMotor]=-armMotorUp; //lower the arm
	while(SensorValue[touchSensor]==touchUnpressed){ //wait for the arm to lower

	}
	motor[armMotor]=0; //stop arm at bottom
}
task main()
{
	//waitForStart();
	toBasket(); //move to basket (forward at 100 power for 600ms)
	cycleArm();
	scaleMove(-100, -100, 150); //reverse for 150
	scaleMove(100, -100, 600); //turn left for 600
	fullStop();
	scaleMove(-100, -100, 830); //away from the baskets in reverse at 100 for 830ms
	fullStop();
	scaleMove(-100, 100, 570); //580
	fullStop();
	scaleMove(100, 100, 1400); //1400
	fullStop();
}
